name: Deploy on GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Install packages
        run: pnpm install

      - name: Build
        run: |
          pnpm build
        env:
          PUBLIC_PATH: /bokolo-mobile-help/

      - name: Push static content into master:gh-pages
        working-directory: .vitepress/dist
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"
          git init
          git add --all
          git commit -m "Auto update pages on $(date +'%Y-%m-%d %H:%M:%S')"
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} master:gh-pages
